name: flutter_sound_record_example
description: Demonstrates how to use the record plugin.
version: 1.0.0

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.1 <3.0.0"
  flutter: ">=2.0.2"

dependencies:
  path_provider: ^2.0.10
  just_audio: ^0.9.21

  flutter:
    sdk: flutter

  flutter_sound_record:
    path: ../

# dependency_overrides:
#   flutter_sound_record_platform_interface:
#     path: ../flutter_sound_record_platform_interface
#   flutter_sound_record_web:
#     path: ../flutter_sound_record_web

dev_dependencies:
  flutter_lints: ^1.0.4

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
