name: flutter_sound_record_web
description: Flutter Record web implementation.
version: 0.3.2
homepage: https://github.com/josephcrowell/flutter_sound_record/tree/master/flutter_sound_record_web

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_sound_record_platform_interface: ^0.3.1

# dependency_overrides:
#   flutter_sound_record_platform_interface:
#     path: ../flutter_sound_record_platform_interface

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterSoundRecordPluginWeb
        fileName: "flutter_sound_record_web.dart"
